:global:
  componentName: keycloak
  githubUrl: https://github.com/projectsyn/component-keycloak
  feature_goUnitTests: true
  feature_goldenTests: true
  testMatrix:
    key: provider
    entries:
      - builtin
      - external
      - openshift

.github/workflows/test.yaml:
  makeTarget: gotest -e instance=${{ matrix.provider }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.provider }}

LICENSE:
  year: 2020

docs/antora.yml:
  name: keycloak
  title: keycloak

.gitignore:
  additionalEntries:
    - jsonnetfile.json

Makefile:
  includes:
    - Makefile.custom.mk
