= Parameters

The parent key for all of the following parameters is `keycloak`.

== `namespace`

[horizontal]
type:: string
default:: `syn-${_instance}`

The namespace in which to deploy this component.

[IMPORTANT]
====
When using multiple instances for this component, each instance needs its own namespace.
You can't deploy multiple instances into the same namespace.
====

== `release_name`

[horizontal]
type:: string
default:: `${_instance}`

Usually there is just one deployment and therefore no change is required.


== `charts.keycloak`

[horizontal]
type:: helm chart version
default:: `10.3.1`

A specific chart version. See the https://kapitan.dev/external_dependencies/#helm-type[kapitan documentation] for more information.


== `fqdn`

[horizontal]
type:: string
default:: `keycloak.example.com`

Defines the FQDN the keycloak ingress or route object is configured.
FQDN should be overwritten on the cluster level.


== `admin.secretname`

[horizontal]
type:: string
default:: `${keycloak:release_name}-admin-user`


== `admin.username`

[horizontal]
type:: string
default:: `admin`


== `admin.password`

[horizontal]
type:: string
default:: Vault reference

A Vault reference pointing to the Vault secret containing the Keycloak admin password.

[source,bash]
----
# Adjust to your environment
instance=keycloak
key="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/${instance}"

# Query for existing secrets first
vault kv get "${key}"

# If there are existing secrets, add your instance secrets:
vault kv patch "${key}" admin-password=$(pwgen -s 32 1)

# If there is no pre-existing secret, create new:
vault kv put "${key}" admin-password=$(pwgen -s 32 1)
----

See xref:how-tos/change-passwords.adoc[Change passwords] to change the password after the initial setup.

== `replicas`

[horizontal]
type:: integer
default:: 2

The Keycloak pod replicas.
Usualy two for the redundancy during the maintenance.


== `secrets`

[horizontal]
type:: dict
default:: `{}`

Additional secrets to be created, for example for TLS certificates.

Example:
[source,yaml]
----
parameters:
  keycloak:
    secrets:
      keycloak-tls:
         tls.crt: "?{vaultkv:${customer:name}/${cluster:name}/${_instance}/keycloak-cert}"
         tls.key: "?{vaultkv:${customer:name}/${cluster:name}/${_instance}/keycloak-cert-key}"
----


== `tls`

[horizontal]
type:: dict
default:: _see below_

This key configures encryption of *internal* traffic, meaning from the IngressController to Keycloak itself.

For Ingress-specific TLS configuration, see `ingress.tls`.


=== `tls.provider`

[horizontal]
type:: string
default:: `secret`

Defines how TLS certificates for internal (ingress to pods) traffic are provisioned:

* `secret` to use a pre-existing secret. See `secrets` above on how to provide one from Vault.
* `openshift` for https://docs.openshift.com/container-platform/4.8/security/certificates/service-serving-certificate.html[service serving certificates].

Also see: `ingress.tls.provider`


=== `tls.secretName`

[horizontal]
type:: string
default:: `keycloak-tls`

The name of the secret where the internal certificate will be stored or taken from


== `service.annotations`

[horizontal]
type:: dict
default:: `{}`

By default, a set of annotations is configured depending on `tls.provider`


== `ingress.enabled`

[horizontal]
type:: bool
default:: `true`

Create an ingress object used usually for standard Kubernetes clusters.


== `ingress.controller`

[horizontal]
type:: string
default:: `nginx`

Defines which ingress controller is used on the cluster.
Used to determine which annotations are required on the ingress object.

Supported options:

* `nginx` - for ingress-nginx (default)
* `openshift` - for OCP4


== `ingress.annotations`

[horizontal]
type:: dict
default:: `{}`

By default, a set of annotations is configured depending on `tls.ingress.provider` and `tls.ingress.termination`.

The default annotations can be extended with custom annotations as required.


== `ingress.controllerNamespace`

[horizontal]
type:: string
default:: `ingress-nginx`

The namespace where the ingress controller is running.
This is only relevant when enabling the network policy with `helm_values.networkPolicy.enabled`.


== `ingress.tls`

[horizontal]
type:: dict
default:: _see below_

This key configures encryption of *external* traffic, meaning from the client to the ingress controller.

For internal TLS configuration, see `tls`.


=== `ingress.tls.termination`

[horizontal]
type:: string
default:: `reencrypt`

Defines the termination mode:

* `reencrypt` TLS termination happens at the ingress or route, then traffic is re-encrypted.
* `passthrough` TLS termination happens at Keycloak itself. Ingress or route passes the traffic.


=== `ingress.tls.provider`

[horizontal]
type:: string
default:: `certmanager`

Defines how TLS certificates for external traffic (Ingress/Route) are provisioned:

* `certmanager` for certificates issued via cert-manager.
* `secret` to use a preexisting secret. See `secrets` above on how to provide one from Vault.

Also see: `tls.provider`


=== `ingress.tls.certmanager.issuer`

[horizontal]
type:: string
default:: `letsencrypt-production`

Name of the ClusterIssuer to use if `certmanager` is selected in `ingress.tls.provider`.


=== `ingress.tls.secretName`

[horizontal]
type:: string
default:: `ingress-tls`

The name of the secret where the ingress certificate will be stored.


== `route.enabled`

[horizontal]
type:: bool
default:: `false`

Create a route object on an OpenShift cluster.


== `labels."app.kubernetes.io/name"`

[horizontal]
type:: string
default:: `keycloak`


== `labels."app.kubernetes.io/instance"`

[horizontal]
type:: string
default:: `${_instance}`


== `labels."app.kubernetes.io/version"`

[horizontal]
type:: string
default:: `v11.0.0`


== `labels."app.kubernetes.io/component"`

[horizontal]
type:: string
default:: `keycloak`


== `labels."app.kubernetes.io/managed-by"`

[horizontal]
type:: string
default:: `commodore`


== `resources.requests.memory`

[horizontal]
type:: string
default:: `512Mi`


== `resources.requests.cpu`

[horizontal]
type:: string
default:: `500m`


== `resources.limits.memory`

[horizontal]
type:: string
default:: `1Gi`


== `resources.limits.cpu`

[horizontal]
type:: string
default:: `1`


== `extraJavaOpts`

[horizontal]
type:: string
default:: ``

The extraJavaOpts can add instance specific configurations to Keycloak.

Example to add a truststore configuration:
[source,yaml]
----
parameters:
  keycloak:
    extraJavaOpts: >-
      -Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/test/truststore.jks
      -Djavax.net.ssl.trustStorePassword=trustStorePass
      -Djavax.net.ssl.trustStoreType=jks
----

Example to increase the log level:
[source,yaml]
----
parameters:
  keycloak:
    extraJavaOpts: >-
      -Djavax.net.debug=all
----


== `extraEnv`

[horizontal]
type:: dict
default:: {}

Extra environment variables added to the Keycloak StatefulSet.
Keys in the dict are used as value for field `name` in the resulting environment variable configuration.
Values must be valid Kubernetes environment variable configurations.


Example:
[source,yaml]
----
parameters:
  keycloak:
    extraEnv:
      FOO:
        value: bar
----

== `extraVolumes`

[horizontal]
type:: dict
default:: {}

Extra volumes added to the Keycloak StatefulSet.
Keys in the dict are used as value for field `name` in the resulting volume configuration.
Values must be valid Kubernetes volume configurations.


Example:
[source,yaml]
----
parameters:
  keycloak:
    extraVolumes:
      theme:
        emptyDir: {}
----

== `extraVolumeMounts`

[horizontal]
type:: dict
default:: {}

Extra volume mounts added to the Keycloak container.
Keys in the dict are used as value for field `name` in the resulting volume mount configuration.
Values must be valid Kubernetes volume mount configurations.

Prefer this over using `helm_values.extraVolumeMounts` since with the later you'll have to make sure you don't accidentially break stuff (for example DB TLS and internal TLS are configured via extra volumes).

Example:
[source,yaml]
----
parameters:
  keycloak:
    extraVolumeMounts:
      theme-vshn:
        name: theme
        readOnly: true
        mountPath: /opt/jboss/keycloak/themes/vshn
----

== `extraInitContainers`

[horizontal]
type:: dict
default:: {}

Extra init containers added to the Keycloak StatefulSet.
Keys in the dict are used as value for field `name` in the resulting container configuration.
Values must be valid Kubernetes container configurations.

Example:
[source,yaml]
----
parameters:
  keycloak:
    extraInitContainers:
      theme-provider:
        image: company/keycloak-theme:v1.0.0
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /theme/* /company-theme
        volumeMounts:
          - name: theme
            mountPath: /company-theme
----

== `monitoring.enabled`

[horizontal]
type:: bool
default:: `true`

Enable ServiceMonitor, PrometheusRule, and all Keycloak statistics on the metrics endpoint by default.


== `monitoring.statistics`

[horizontal]
type:: string
default:: `all`


== `monitoring.rules`

[horizontal]
type:: list
default:: `[]`

== `database.provider`

[horizontal]
type:: string
values:: `builtin`, `external`
default:: `builtin`


== `database.database`

[horizontal]
type:: string
default:: `keycloak`


== `database.username`

[horizontal]
type:: string
default:: `keycloak`


== `database.jdbcParams`

[horizontal]
type:: string
default:: `sslmode=verify-ca&sslrootcert=/opt/jboss/certs/tls.crt`

Please note that if you need to customize JDBC parameters, copy and append them to the default with `&`, otherwise TLS will be disabled.
For example: `sslmode=verify-ca&sslrootcert=/opt/jboss/certs/tls.crt&mycustomparameter=somevalue`


== `database.password`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/${_instance}/db-password}`

A Vault reference pointing to the Vault secret containing the Keycloak database password.

[source,bash]
----
# Adjust to your environment
instance=keycloak
key="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/${instance}"

# Query for existing secrets first
vault kv get "${key}"

# If there are existing secrets, add your instance secrets:
vault kv patch "${key}" db-password=$(pwgen -s 32 1)

# If there is no pre-existing secret, create new:
vault kv put "${key}" db-password=$(pwgen -s 32 1)
----

See xref:how-tos/change-passwords.adoc[Change passwords] to change the password after the initial setup.

== `database.secretname`

[horizontal]
type:: string
default:: `${keycloak:release_name}-postgresql`


== `database.external.vendor`

[horizontal]
type:: string
default:: `postgres`


== `database.external.host`

[horizontal]
type:: string
default:: `postgres.example.com`


== `database.external.port`

[horizontal]
type:: int
default:: `5432`

== `database.tls.enabled`

[horizontal]
type:: bool
default:: `true`

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption or to disable it completely.


== `database.tls.verification`

[horizontal]
type:: string
values:: `selfsigned`, `verify`
default:: `selfsigned`


== `database.tls.certSecretName`

[horizontal]
type:: string
default:: `keycloak-postgresql-tls`


== `database.tls.serverCert`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/${_instance}/server-cert}`

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption.


== `database.tls.serverCertKey`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/${_instance}/server-cert-key}`

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption.


== `k8up.enabled`

[horizontal]
type:: bool
default:: `false`

Defines whether the K8up database backup is enabled or not.


== `k8up.keepjobs`

[horizontal]
type:: int
default:: `3`

Defines how many backup jobs are kept.
It's useful for debugging to have a few recent completed (or failed) backup jobs available in K8s.
Keeping a lot of jobs may negatively impact the K8s cluster performance however.


== `k8up.repo.secretName`

[horizontal]
type:: string
default:: `k8up-repo`

The name of the secret containing the password for the K8up restic repository.


== `k8up.repo.password`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/keycloak/k8up-repo-password}`

Vault reference to the K8up restic repository password.


== `k8up.s3.secretName`

[horizontal]
type:: string
default:: `k8up-s3-credentials`

The name of the secret containing the credentials to access the S3 bucket holding the backups.


== `k8up.s3.bucket`

[horizontal]
type:: string
default:: `k8up-${cluster:name}-syn-keycloak`

The name of the S3 bucket where the backups gets stored.


== `k8up.s3.accessKey`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/keycloak/k8up-s3-accesskey}`

S3 access key to the bucket where the backups gets stored.


== `k8up.s3.secretKey`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/keycloak/k8up-s3-secretkey}`

S3 secret key to the bucket where the backups gets stored.


== `helm_values`

[horizontal]
type:: dict
default:: see `defaults.yml`

All helm_values are passed to the helm chart.
This allows to configure all https://github.com/codecentric/helm-charts/tree/keycloak-10.3.1/charts/keycloak#configuration[keycloak helm chart values].

Note that it's your own liability to make sure you don't break stuff by overwriting values here!
