= Parameters

The parent key for all of the following parameters is `keycloak`.

== `namespace`

[horizontal]
type:: string
default:: `syn-${_instance}`

The namespace in which to deploy this component.

[IMPORTANT]
====
When using multiple instances for this component, each instance needs its own namespace.
You cannot deploy multiple instances into the same namespace.
====

== `release_name`

[horizontal]
type:: string
default:: `${_instance}`

Usually there is just one deployment and therefore no change is required.


== `charts.keycloak`

[horizontal]
type:: helm chart version
default:: `10.3.1`

A specific chart version. See the https://kapitan.dev/external_dependencies/#helm-type[kapitan documentation] for more information.


== `fqdn`

[horizontal]
type:: string
default:: `keycloak.example.com`

Defines the FQDN the keycloak ingress or route object is configured.
FQDN should be overwritten on the cluster level.


== `admin.secretname`

[horizontal]
type:: string
default:: `${keycloak:release_name}-admin-user`


== `admin.username`

[horizontal]
type:: string
default:: `admin`


== `admin.password`

[horizontal]
type:: string
default:: Vault reference

A Vault reference pointing to the Vault secret containing the Keycloak admin password.

[source,bash]
----
# Adjust to your environment
instance=keycloak
key="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/${instance}"

# Query for existing secrets first
vault kv get "${key}"

# If there are existing secrets, add your instance secrets:
vault kv patch "${key}" admin-password=$(pwgen -s 32 1)

# If there is no pre-existing secret, create new:
vault kv put "${key}" admin-password=$(pwgen -s 32 1)
----

See xref:how-tos/change-passwords.adoc[Change passwords] to change the password after the initial setup.

== `replicas`

[horizontal]
type:: integer
default:: 2

The Keycloak pod replicas.
Usualy two for the redundancy during the maintenance.


== `tls.variant`

[horizontal]
type:: string
default:: `certmanager`

Defines the variant how TLS certificates are deployed:

* `certmanager` for certificates issued via cert-manager
* `vault` for certificates stored in Vault


== `tls.termination`

[horizontal]
type:: string
default:: `passthrough`

Defines the termination mode:

* `passthrough` TLS termination happens at Keycloak itself, ingress or route passes the traffic
* `reencrypt` TLS termination happens at the ingress or route, the traffic is reencrypted


== `tls.secretName`

[horizontal]
type:: string
default:: `passthrough`


== `tls.vault.cert`

[horizontal]
type:: string
default:: Vault reference


== `tls.vault.cert`

[horizontal]
type:: String
default:: Vault reference


== `tls.certmanager.issuer.name`

[horizontal]
type:: string
default:: `letsencrypt-production`

Define the issuer name. This is usualy `letsencrypt-production` or `letsencrypt-staging`.


== `tls.certmanager.issuer.kind`

[horizontal]
type:: string
default:: `ClusterIssuer`

Define the issuer kind. Can be `ClusterIssuer` or `Issuer`.


== `tls.certmanager.issuer.group`

[horizontal]
type:: string
default:: `cert-manager.io`


== `ingress.enabled`

[horizontal]
type:: bool
default:: `false`

Create an ingress object used usually for standard Kubernetes clusters.


== `ingress.controller`

[horizontal]
type:: string
default:: `nginx`

Does define the used ingress controller on the cluster side.

Defaults to `nginx` and this is currently also the only valid option.


== `ingress.annotations`

[horizontal]
type:: dict
default:: `{}`

Default takes predefined annotations configured from `tls.variant` and `tls.termination`.

The default can always be replaced by an own definition of annotations.

An example shows how to allow an automatic ACME based certificate creation via cert-manager:
[source,yaml]
----
parameters:
  keycloak:
    ingress:
      annotations:
        kubernetes.io/tls-acme: 'true'
        cert-manager.io/cluster-issuer: letsencrypt-production
----


== `ingress.secretName`

[horizontal]
type:: string
default:: `ingress-tls`

Deprecated see `ingress.tls.secretName`.


== `ingress.controllerNamespace`

[horizontal]
type:: string
default:: `ingress-nginx`

The namespace where the ingress controller is running.
This is only relevant when enabling the network policy with `helm_values.networkPolicy.enabled`.


== `ingress.tls.secretName`

[horizontal]
type:: string
default:: `ingress-tls`

Allows overwriting the default TLS secret name of `ingress-tls`.


== `ingress.tls.vault.enabled`

[horizontal]
type:: bool
default:: `Depends on ${keycloak:tls:variant} ${keycloak:tls:termination}`

Create ingress-tls certificate, if `${keycloak:tls:variant}` is `vault` and the `${keycloak:tls:termination}` is
`reencrypt`.


== `ingress.tls.vault.enabled`

[horizontal]
type:: bool
default:: `Depends on ${keycloak:tls:variant} ${keycloak:tls:termination}`


== `ingress.tls.vault.cert`

[horizontal]
type:: string
default:: Vault reference


== `ingress.tls.vault.certKey`

[horizontal]
type:: string
default:: Vault reference


== `route.enabled`

[horizontal]
type:: bool
default:: `false`

Create a route object on an OpenShift cluster.


== `labels."app.kubernetes.io/name"`

[horizontal]
type:: string
default:: `keycloak`


== `labels."app.kubernetes.io/instance"`

[horizontal]
type:: string
default:: `${_instance}`


== `labels."app.kubernetes.io/version"`

[horizontal]
type:: string
default:: `v11.0.0`


== `labels."app.kubernetes.io/component"`

[horizontal]
type:: string
default:: `keycloak`


== `labels."app.kubernetes.io/managed-by"`

[horizontal]
type:: string
default:: `commodore`


== `resources.requests.memory`

[horizontal]
type:: string
default:: `512Mi`


== `resources.requests.cpu`

[horizontal]
type:: string
default:: `500m`


== `resources.limits.memory`

[horizontal]
type:: string
default:: `1Gi`


== `resources.limits.cpu`

[horizontal]
type:: string
default:: `1`


== `extraJavaOpts`

[horizontal]
type:: string
default:: ``

The extraJavaOpts can add instance specific configurations to Keycloak.

Example to add a truststore configuration:
[source,yaml]
----
parameters:
  keycloak:
    extraJavaOpts: >-
      -Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/test/truststore.jks
      -Djavax.net.ssl.trustStorePassword=trustStorePass
      -Djavax.net.ssl.trustStoreType=jks
----

Example to increase the log level:
[source,yaml]
----
parameters:
  keycloak:
    extraJavaOpts: >-
      -Djavax.net.debug=all
----


== `monitoring.enabled`

[horizontal]
type:: bool
default:: `true`

Enable ServiceMonitor, PrometheusRule, and all Keycloak statistics on the metrics endpoint by default.


== `monitoring.statistics`

[horizontal]
type:: string
default:: `all`


== `monitoring.rules`

[horizontal]
type:: list
default:: `[]`

== `database.provider`

[horizontal]
type:: string
values:: `builtin`, `external`
default:: `builtin`


== `database.database`

[horizontal]
type:: string
default:: `keycloak`


== `database.username`

[horizontal]
type:: string
default:: `keycloak`


== `database.jdbcParams`

[horizontal]
type:: string
default:: `sslmode=verify-ca&sslrootcert=/opt/jboss/certs/tls.crt`

Please note that if you need to customize JDBC parameters, copy and append them to the default with `&`, otherwise TLS will be disabled.
For example: `sslmode=verify-ca&sslrootcert=/opt/jboss/certs/tls.crt&mycustomparameter=somevalue`


== `database.password`

[horizontal]
type:: string
default:: Vault reference

A Vault reference pointing to the Vault secret containing the Keycloak database password.

[source,bash]
----
# Adjust to your environment
instance=keycloak
key="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/${instance}"

# Query for existing secrets first
vault kv get "${key}"

# If there are existing secrets, add your instance secrets:
vault kv patch "${key}" db-password=$(pwgen -s 32 1)

# If there is no pre-existing secret, create new:
vault kv put "${key}" db-password=$(pwgen -s 32 1)
----

See xref:how-tos/change-passwords.adoc[Change passwords] to change the password after the initial setup.

== `database.secretname`

[horizontal]
type:: string
default:: `${keycloak:release_name}-postgresql`


== `database.external.vendor`

[horizontal]
type:: string
default:: `postgres`


== `database.external.host`

[horizontal]
type:: string
default:: `postgres.example.com`


== `database.external.port`

[horizontal]
type:: int
default:: `5432`

== `database.tls.enabled`

[horizontal]
type:: bool
default:: `true`

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption or to disable it completely.


== `database.tls.verification`

[horizontal]
type:: string
values:: `selfsigned`, `verify`
default:: `selfsigned`


== `database.tls.certSecretName`

[horizontal]
type:: string
default:: `keycloak-postgresql-tls`


== `database.tls.serverCert`

[horizontal]
type:: string
default:: Vault reference

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption.


== `database.tls.serverCertKey`

[horizontal]
type:: string
default:: Vault reference

See xref:how-tos/db-tls.adoc[Encrypt database connection] to install Keycloak with encryption.


== `helm_values`

[horizontal]
type:: dict
default:: see `defaults.yml`

All helm_values are passed to the helm chart.
This allows to configure all https://github.com/codecentric/helm-charts/tree/keycloak-10.3.1/charts/keycloak#configuration[keycloak helm chart values].
