= Configure Keycloak ingress

Incoming network traffic to the Keycloak service is usually routed via an ingress or a route object for OpenShift.

== Ingress over an NGINX Controller

. In a first step the ingress object needs to be enabled
+
[source,bash]
----
parameters:
  keycloak:
    ingress:
      enabled: true
----

. Configure the ingress controller (can be skipped as it is the default value)
+
[source,bash]
----
parameters:
  keycloak:
    ingress:
      controller: nginx
----

. Choose where the TLS session to Keycloak is terminated

.. Terminate the TLS session on the ingress and on Keycloak
+
[source,bash]
----
parameters:
  keycloak:
    tls:
      termination: reencrypt
----
+
This requires Keycloak has a self singed certificate.
See xref:how-tos/keycloak-tls.adoc[Setup a TLS certificate for Keycloak].

.. Terminate the TLS session direct on Keycloak
+
[source,bash]
----
parameters:
  keycloak:
    tls:
      termination: passthrough
----
+
This requires also that the NGINX Controller is configured to pass through the TLS traffic.
This is not enabled by default:
+
[source,bash]
----
parameters:
  ingress_nginx:
    helm_values:
      controller:
        extraArgs:
          enable-ssl-passthrough: true
----
+
. Configure how the certificates being issued
+
.. If you plan to use the cert-manager to issue certificates:
+
[source,bash]
----
parameters:
  keycloak:
    tls:
      variant: certmanager
----
+
By default certificates are issued from Let's encrypt.
+
.. Manually issued certificates stored in vault:
+
[source,bash]
----
parameters:
  keycloak:
    tls:
      variant: vault
----
+
See xref:how-tos/keycloak-tls.adoc[Setup a TLS certificate for Keycloak] for how to create a certificate.
