= Installing on OpenShift 4

This guide describes how to install this component on OpenShift 4.

== Parameters for Keycloak

You need to disable some security context fields, as OpenShift sets those automatically.
Also, the sample below configures end-to-end encryption to Keycloak with https://docs.openshift.com/container-platform/4.9/security/certificates/service-serving-certificate.html[OpenShift service serving certificate].

[source,yaml,subs="attributes+"]
----
parameters:
  keycloak:
    tls:
      provider: openshift
    ingress:
      tls:
        termination: reencrypt
    extraVolumes:
      data:
        emptyDir: {}
    extraVolumeMounts:
      # Required as the OpenShift user can not create the data directory in the keycloak directory UID 1000/GID 0
      data:
        mountPath: /opt/keycloak/data
    helm_values:
      podSecurityContext: null
      securityContext: null
      dbchecker:
        securityContext: null
----

== Parameters for built-in Postgresql database on OpenShift 4.11 and higher

If you are using the built-in database provider (by default unless `keycloak.database.provider` is overridden) you also need to adjust the following parameters.

[source,yaml,subs="attributes+"]
----
parameters:
  keycloak:
    postgresql_helm_values:
      primary:
        podSecurityContext:
          enabled: true
          fsGroup: null
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          enabled: true
          runAsUser: null
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      volumePermissions:
        enabled: false
      shmVolume:
        enabled: false
----

== Parameters for built-in Postgresql database up to OpenShift 4.10

If you are using the built-in database provider (by default unless `keycloak.database.provider` is overridden) you also need to adjust the following parameters.

[source,yaml,subs="attributes+"]
----
parameters:
  keycloak:
    postgresql_helm_values:
      primary:
        podSecurityContext:
          enabled: false
        containerSecurityContext:
          enabled: false
      volumePermissions:
        enabled: false
      shmVolume:
        enabled: false
----
