name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
    steps:
      - uses: actions/checkout@v2
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
