name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: keycloak

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - builtin
          - external
          - openshift
          - openshift-postgres
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." tests/go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Compile component
        run: make gotest -e instance=${{ matrix.provider }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - builtin
          - external
          - openshift
          - openshift-postgres
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.provider }}
